"""empty message

Revision ID: 4e6cd047cfc3
Revises: 
Create Date: 2018-08-15 09:37:06.253974

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4e6cd047cfc3'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('movie',
    sa.Column('m_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('m_name', sa.String(length=32), nullable=True),
    sa.PrimaryKeyConstraint('m_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('movie')
    # ### end Alembic commands ###
