"""empty message

Revision ID: 8a3c7a3d27e9
Revises: 5f2c5108ef26
Create Date: 2018-08-14 15:36:10.352682

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8a3c7a3d27e9'
down_revision = '5f2c5108ef26'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('movie',
    sa.Column('m_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('m_name', sa.String(length=16), nullable=True),
    sa.PrimaryKeyConstraint('m_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('movie')
    # ### end Alembic commands ###
